### ISSUE TITLE
boost/variant/detail/multivisitors_cpp14_based.hpp # includes itself

### ISSUE THREAD

**Issue by urnathan** [boostorg/variant#101]
working on using clang modules (as a proxy for C++20 header units), I found that boost/variant/detail/multivisitors_cpp14_based.hpp includes itself.  That seems unnatural :)

[boost-includes.txt](https://github.com/boostorg/variant/files/9447173/boost-includes.txt)

**Comment by apolukhin** [comment]
Many thanks for the report!
