### ISSUE TITLE
Unable to compile a project using recursive variant under MSVC 2017 15.5 with compiler switch /std:c++17 and /std:c++latest

### ISSUE THREAD

**Issue by jhruby** [boostorg/variant#42]
15.4 compiler compiles with all flags std flags without any issues. 15.5 version is unable to compile correctly  /std:c++17 and /std:c++latest.

Check out the library:
https://github.com/no1msd/mstch

Configure CMAKE and CMAKE_CXX_FLAGS += /std:c++17

After opening project under visual studio compilation fails:
[compiler-output.txt](https://github.com/boostorg/variant/files/1541884/compiler-output.txt)

Please note that switches /std:c++11 and /std:c++14 are working correctly.

Thanks

**Comment by egorpugin** [comment]
Same for me.

**Comment by egorpugin** [comment]
Simple repro:
```
#include <boost/variant.hpp>

#include <memory>

int main()
{
    using node = boost::make_recursive_variant<
        int,
        std::shared_ptr<boost::recursive_variant_>
    >::type;

    node x = 1;
}
```

(Almost) original case from mstch.
```

#include <boost/variant.hpp>

#include <map>
#include <memory>
#include <vector>

int main()
{
    using node = boost::make_recursive_variant<
        std::nullptr_t, std::string, int, double, bool,
        std::shared_ptr<boost::recursive_variant_>,
        std::map<const std::string, boost::recursive_variant_>,
        std::vector<boost::recursive_variant_>>::type;

    node x = 1;
}
```

Both works on VS15.5 in C++14 mode, does not work in C++17 mode.

**Comment by egorpugin** [comment]
This works for me as a workaround.
```
#define BOOST_VARIANT_DO_NOT_USE_VARIADIC_TEMPLATES
#include <mstch/mstch.hpp>
```

**Comment by jhruby** [comment]
Thanks for work around this could let me upgrade visual studio :)

**Comment by Kojoley** [comment]
Other workaround `#define BOOST_VARIANT_DETAIL_NO_SUBSTITUTE`

**Comment by apolukhin** [comment]
Many thanks for providing tests and fixes!
Merged to develop, will be merged to master branch after the regression tests cycle.
