### ISSUE TITLE
Feature request: optimization for types with common base class

### ISSUE THREAD

**Issue by HDembinski** [boostorg/variant#50]
It would be great if the variant could skip the visitation loop when all bound types have a common base type, and the user tries to cast the variant to the common base type.

Pseudo-code:
```
struct A {};
struct B : A {};
struct C : A {};

boost::variant<B, C> v(B());
A& a = boost::get<A>(v); // no visitation needed, because A is a common base type of all bounded types
```
I am using boost::variant as a backend in [histogram](https://github.com/hdembinski/histogram) and this would allow me to speed up a part of the code. I think it is a useful feature for others as well.

**Comment by HDembinski** [comment]
I looked into the code, I think this can work and would merely require some changes to `boost::get`. TMP can figure out whether the requested type is a common base of all bounded types. Based on static decision, the either fast implementation with a direct `static_cast` can be used or the slow visitation version.

**Comment by apolukhin** [comment]
That's an interesting idea for the compiler developers rather than for the Boost.Variant.

I'll try to simplify your example and fill an issue for the Clang and GCC.

**Comment by apolukhin** [comment]
Looks like modern compilers already do that for simple cases: https://godbolt.org/g/FdZjmT
For more complex cases GCC fails to eliminate the checks: https://godbolt.org/g/rpXEvD

**Comment by HDembinski** [comment]
Yeah, you are right. I had a discussion with @mattcalabrese on Slack on this, and they convinced me that my original naive idea to just reinterpret cast the aligned storage holder in boost::variant to the base is UB.

Then I found that - at least for my case and with gcc - the visitation in boost::variant is optimized away if I make a visitor that just casts to the base.
https://godbolt.org/g/qNDWme

I don't fully understand the assembler, but I look like the visitation is skipped and there is only one error check at the end. When you increase the number of derived classes, the assembler code has the same length. So that's good. It is not as efficient as your first example, but I am still pretty impressed.

So, feel free to close this request.

**Comment by apolukhin** [comment]
Yes, everything is fine with `boost::variant`, however GCC and Clang fail to optimize the `std::variant` from libstdc++ in the same way https://godbolt.org/g/UaHt7Q . So some day, after the migration to C++17, you may get hit by this issue.

I've minimized the example and filled bugs on GCC and Clang
* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86909
* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86912
* https://bugs.llvm.org//show_bug.cgi?id=34801 (Actually I've filled this one a long time ago)

And only now I'm OK with closing this request :)

P.S.: Subscribing to the bugs may improve the chances of the bug to be fixed sooner. :)

**Comment by HDembinski** [comment]
Cool, this is great. Sorry, I wasn't trying to tell you what you should do and what not or when, I just wanted to be friendly :)

**Comment by apolukhin** [comment]
Do not apologize. I've just wanted to look cool :)

BTW, here's another related issue https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78113
