### ISSUE TITLE
-DBOOST_VARIANT_VISITATION_UNROLLING_LIMIT=1 produces significantly better codegen on Clang

### ISSUE THREAD

**Issue by pdimov** [boostorg/variant#60]
The current visitation implementation always generates a switch with 20 cases, regardless of the number of alternatives in the variant. For the common case of 2-6 alternatives, this is a significant pessimization under Clang, because it doesn't inline the visitation: f.ex. https://godbolt.org/z/TxiL_G

With -DBOOST_VARIANT_VISITATION_UNROLLING_LIMIT=1, Clang is smart enough to turn the recursive calls back into a switch, with the correct number of cases: https://godbolt.org/z/3Zxu4X

This results in a measurable difference, which I discovered because I was asked to produce benchmarks of Variant2, see f.ex.

https://github.com/pdimov/variant2/blob/develop/benchmark/benchmark1.md
https://github.com/pdimov/variant2/blob/develop/benchmark/benchmark2.md

where Boost.Variant suffers because of this issue, but is significantly faster than the competition with -DBOOST_VARIANT_VISITATION_UNROLLING_LIMIT=1 under both g++ and clang++.

Perhaps the decision to use the preprocessor-based unrolled switch needs to be revisited for the more modern compilers.

**Comment by Kojoley** [comment]
Strange. I saw no a long ago somewhere (most likely on GCC bugtracker) that `boost::variant` is faster than `std::variant` because of using switch and those folks suggested to make something like this to libstdc++ implementation.

**Comment by apolukhin** [comment]
Looks like GCC also generates a better code with `-DBOOST_VARIANT_VISITATION_UNROLLING_LIMIT=1`.

Good news everyone! It means that I can drop the macro stuff and just leave the recursive calls. This should simplify the code, improve the build times and make the library more modules friendly :)

**Comment by Kojoley** [comment]
Interesting, it contradicts https://github.com/mpark/variant/pull/56.

**Comment by pdimov** [comment]
You can always try the benchmark and see, I suppose.

**Comment by apolukhin** [comment]
> Interesting, it contradicts [mpark/variant#56](https://github.com/mpark/variant/pull/56).

It looks that the initial version was using type erased array of functions (just like GCCs std::variant does). Compilers are bad in inlining and optimizing functions by function pointer https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86912

I assume that `switch` is faster than an array of functions, while the trivial tail recursion is faster than `switch`.

**Comment by pdimov** [comment]
The problem with the current implementation is not that it's a switch, but that it's a switch with 20 cases. When the variant has only three alternatives, the optimal switch has three (or four) cases, not 20. (In fact, the compilers turn the tail recursion back into a switch.)

**Comment by apolukhin** [comment]
I've done a small research. Note that the DIFF View is often messed up when using the links (so you have to manually adjust it):
* With small amount of types in variant https://godbolt.org/z/YtUYIb and -DBOOST_VARIANT_VISITATION_UNROLLING_LIMIT=1 assembly is:
    * much better on Clang (it removes the crazy jump tables... Those were already noted in https://bugs.llvm.org/show_bug.cgi?id=39254 )
    * exactly the same on GCC
    * much worse on MSVC
* With a lot of of types in variant https://godbolt.org/z/6GIZUU and -DBOOST_VARIANT_VISITATION_UNROLLING_LIMIT=1 assembly is:
    * slightly worse on Clang
    * much better on GCC
    * better on MSVC

I was weighting the assembly quality mostly be the amount of assembly data in the result.

The whole story has a bad small. In ideal world compilers should be able to optimize the switch with any value of `BOOST_VARIANT_VISITATION_UNROLLING_LIMIT` to the same assembly. With values other than 1 it could be a little bit harder and will add some compile time overhead for small amount of types.

Right now I'm in favor of leaving the `BOOST_VARIANT_VISITATION_UNROLLING_LIMIT` as is.

**Comment by Kojoley** [comment]
It seems that GCC throws away the unreachable switch cases while Clang not. Placing `__builtin_unreachable` inside `forced_return` heals the things for Clang.

**Comment by apolukhin** [comment]
Seems that `forced_return` changed the picture and now all the compilers produce quite the same assembly in most cases: https://godbolt.org/z/dJqYjc and https://godbolt.org/z/UDGLJF

However `BOOST_VARIANT_VISITATION_UNROLLING_LIMIT=1` produces shorter codegen for MSVC.

**Comment by apolukhin** [comment]
`BOOST_VARIANT_VISITATION_UNROLLING_LIMIT=1` speeds up compilation:
time ../../../b2 toolset=clang-9,gcc-8 cxxstd=14,11,03,98 -j4 -a
with defaults, second run:
```
real    6m25.725s
user    22m41.421s
sys    1m17.262s
```
vs `BOOST_VARIANT_VISITATION_UNROLLING_LIMIT=1` run
```
real    6m18.966s
user    22m9.030s
sys    1m14.541s

**Comment by Kojoley** [comment]
There are two key differences between them:
  1. Clang handles branches and switches the same way, it is able to combine branches into switches https://godbolt.org/z/6tkZNw and to merge switches https://godbolt.org/z/P7wGPB together, while GCC and MSVC are not able to do anything of that. The GCC bug reports are https://gcc.gnu.org/bugzilla/show_bug.cgi?id=14799 and https://gcc.gnu.org/bugzilla/show_bug.cgi?id=93326; you seem to be following one of them :-)
  2. GCC is able to merge same switch cases while others are not. Because of that GCC does not even hit a jumptable generation threshold and the resulting asm is same for both cases (`BOOST_VARIANT_VISITATION_UNROLLING_LIMIT=1` and default).

385s vs 378s is about 2% difference, it could be just dynamic clocking fluctuation if you did not turn it off or/and took measurement multiple times.

**Comment by apolukhin** [comment]
I've measured multiple times, the difference in time holds. But it is minor, you're right.

**Comment by apolukhin** [comment]
I'm closing this issue: there's no solution that improves all the compilers codegens in all the workloads.
