### ISSUE TITLE
GCC suggest-override warnings

### ISSUE THREAD

**Issue by EugeneZelenko** [boostorg/variant#78]
GCC 7.5 fires suggest-override warnings in Boost 1.72:

<pre>
include/boost/variant/get.hpp:47:26: error: ‘virtual const char* boost::bad_get::what() const’ can be marked override [-Werror=suggest-override]
include/boost/variant/bad_visit.hpp:31:26: error: ‘virtual const char* boost::bad_visit::what() const’ can be marked override [-Werror=suggest-override]
</pre>

**Comment by EugeneZelenko** [comment]
Related: boostorg/config#253

**Comment by apolukhin** [comment]
Thanks for the report!

**Comment by EugeneZelenko** [comment]
Thank you for help!
