### ISSUE TITLE
Bad usage of `boost::move` causes `boost::apply_visitor` to fail in certain cases

### ISSUE THREAD

**Issue by akrzemi1** [boostorg/variant#82]
The following program fails to compile:

```c++
#include <boost/thread/locks.hpp> // REMOVE this include and program will compile
#include <boost/variant.hpp>

boost::variant<int> make_variant() {
    return 1;
}

int main() {
    auto visitor = [](auto&&) {};
    boost::apply_visitor(visitor, make_variant());
}
```

Here is a Wandbox link:
https://wandbox.org/permlink/p55KKRYU3jqjZbIr

Removing the `#include` of Boost.Thread helps because the latter provides an overload of `boost::move()`; however, the problem is caused by the use of `boost::move()` in `<boost/variant/variant.hpp>` at https://github.com/boostorg/variant/blob/master/include/boost/variant/variant.hpp#L1021

Function `internal_visit` provides template parameters to `boost::move()` explicitly, which disables SFINAE and causes the overload from Boost.Thread to fail.

**Comment by apolukhin** [comment]
Many many many thanks for the description of the fix! I've been scratching my head since #53 and could not locate the bad usage
