### ISSUE TITLE
Problems with Boost Variant

### ISSUE THREAD

**Issue by pschaeffer** [boostorg/variant#84]
The program below does not compile. It is quite simple and you would think that it would.

#include "boost/variant.hpp"
class PROgOperTypes {
public:
  enum operTypesEnum : int8_t {
    anyOk     
  };
  PROgOperTypes(operTypesEnum type) : enumValue(type) {}
  operTypesEnum  enumValue;
};
int main() {
  typedef boost::variant<double, int64_t>  PROgValueVariant;
  PROgValueVariant dummyVar = PROgOperTypes::anyOk;
}

What am I doing wrong? Note that adding PROgOperTypes to the variant does not fix the problem. I should say that I am using Boost 1_72 so I should be reasonably up-to-date.

**Comment by pschaeffer** [comment]
Thank you folks

**Comment by apolukhin** [comment]
That is an intended behavior, `std::variant` does not compile in the same manner: https://godbolt.org/z/nT9qcc

Adding an explicit `static_cast` to the sample fixes the compilation: https://godbolt.org/z/KMz1Pj

**Comment by pschaeffer** [comment]
Mr. Apolukhin,
Wow. That fixed it. 
Thank you
Peter Schaeffer
